# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\wkspaces\aspe_gui\views\uis\data_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_data_wiewer_widget(object):
    def setupUi(self, data_wiewer_widget):
        data_wiewer_widget.setObjectName("data_wiewer_widget")
        data_wiewer_widget.resize(710, 630)
        self.widget_layout = QtWidgets.QVBoxLayout(data_wiewer_widget)
        self.widget_layout.setContentsMargins(3, 3, 3, 3)
        self.widget_layout.setSpacing(3)
        self.widget_layout.setObjectName("widget_layout")
        self.groupBox = QtWidgets.QGroupBox(data_wiewer_widget)
        self.groupBox.setObjectName("groupBox")
        self.group_box_layout = QtWidgets.QVBoxLayout(self.groupBox)
        self.group_box_layout.setObjectName("group_box_layout")
        self.label_combo_box_layout = QtWidgets.QGridLayout()
        self.label_combo_box_layout.setObjectName("label_combo_box_layout")
        self.data_source_label = QtWidgets.QLabel(self.groupBox)
        self.data_source_label.setObjectName("data_source_label")
        self.label_combo_box_layout.addWidget(self.data_source_label, 0, 0, 1, 1)
        self.data_source_combo_box = QtWidgets.QComboBox(self.groupBox)
        self.data_source_combo_box.setObjectName("data_source_combo_box")
        self.label_combo_box_layout.addWidget(self.data_source_combo_box, 0, 1, 1, 1)
        self.group_box_layout.addLayout(self.label_combo_box_layout)
        self.data_source_stacked_widget = QtWidgets.QStackedWidget(self.groupBox)
        self.data_source_stacked_widget.setObjectName("data_source_stacked_widget")

        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.data_set_only_curr_scan_layout = QtWidgets.QGridLayout()
        self.data_set_only_curr_scan_layout.setObjectName("data_set_only_curr_scan_layout")
        self.data_set_label = QtWidgets.QLabel(self.page)
        self.data_set_label.setObjectName("data_set_label")
        self.data_set_only_curr_scan_layout.addWidget(self.data_set_label, 0, 0, 1, 1)
        self.data_set_combo_box = QtWidgets.QComboBox(self.page)
        self.data_set_combo_box.setObjectName("data_set_combo_box")
        self.data_set_only_curr_scan_layout.addWidget(self.data_set_combo_box, 0, 1, 1, 1)
        self.only_curr_scan_label = QtWidgets.QLabel(self.page)
        self.only_curr_scan_label.setObjectName("only_curr_scan_label")
        self.data_set_only_curr_scan_layout.addWidget(self.only_curr_scan_label, 1, 0, 1, 1)
        self.current_scan_check_box = QtWidgets.QCheckBox(self.page)
        self.current_scan_check_box.setText("")
        self.current_scan_check_box.setObjectName("current_scan_check_box")
        self.data_set_only_curr_scan_layout.addWidget(self.current_scan_check_box, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.data_set_only_curr_scan_layout)
        self.data_set_stacked_widget = QtWidgets.QStackedWidget(self.page)
        self.data_set_stacked_widget.setObjectName("data_set_stacked_widget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.page_3)
        self.tabWidget.setObjectName("tabWidget")
        self.signals_tab = QtWidgets.QWidget()
        self.signals_tab.setObjectName("signals_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.signals_tab)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.signals_table = QtWidgets.QTableWidget(self.signals_tab)
        self.signals_table.setObjectName("signals_table")
        self.signals_table.setColumnCount(2)
        self.signals_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.signals_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.signals_table.setHorizontalHeaderItem(1, item)
        self.signals_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.signals_table)
        self.tabWidget.addTab(self.signals_tab, "")
        self.raw_signals_tab = QtWidgets.QWidget()
        self.raw_signals_tab.setObjectName("raw_signals_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.raw_signals_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.raw_signals_table = QtWidgets.QTableWidget(self.raw_signals_tab)
        self.raw_signals_table.setObjectName("raw_signals_table")
        self.raw_signals_table.setColumnCount(0)
        self.raw_signals_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.raw_signals_table)
        self.tabWidget.addTab(self.raw_signals_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.data_set_stacked_widget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.data_set_stacked_widget.addWidget(self.page_4)
        self.verticalLayout_4.addWidget(self.data_set_stacked_widget)

        self.data_source_stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.data_source_stacked_widget.addWidget(self.page_2)
        self.group_box_layout.addWidget(self.data_source_stacked_widget)
        self.widget_layout.addWidget(self.groupBox)

        self.retranslateUi(data_wiewer_widget)
        self.data_source_stacked_widget.setCurrentIndex(0)
        self.data_set_stacked_widget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(data_wiewer_widget)

    def retranslateUi(self, data_wiewer_widget):
        _translate = QtCore.QCoreApplication.translate
        data_wiewer_widget.setWindowTitle(_translate("data_wiewer_widget", "Form"))
        self.groupBox.setTitle(_translate("data_wiewer_widget", "DataViewer"))
        self.data_source_label.setText(_translate("data_wiewer_widget", "DataSource"))
        self.data_set_label.setText(_translate("data_wiewer_widget", "DataSet"))
        self.only_curr_scan_label.setText(_translate("data_wiewer_widget", "OnlyCurrentScan"))
        item = self.signals_table.horizontalHeaderItem(0)
        item.setText(_translate("data_wiewer_widget", "signal"))
        item = self.signals_table.horizontalHeaderItem(1)
        item.setText(_translate("data_wiewer_widget", "value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signals_tab), _translate("data_wiewer_widget", "Signals"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.raw_signals_tab), _translate("data_wiewer_widget", "RawSignals"))
