# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\wkspaces\aspe_gui\views\uis\playback_panel_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_PlaybackPanelWidget(QtWidgets.QWidget):
    def setupUi(self):
        self.setObjectName("PlaybackPanelWidget")
        self.widget_layout = QtWidgets.QVBoxLayout(self)
        self.widget_layout.setContentsMargins(0,0,0,0)
        self.group_box = QtWidgets.QGroupBox(self)
        self.group_box.setTitle('PlaybackPanel')
        self.widget_layout.addWidget(self.group_box)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.group_box)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.control_buttons_widget = QtWidgets.QWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_buttons_widget.sizePolicy().hasHeightForWidth())
        self.control_buttons_widget.setSizePolicy(sizePolicy)
        self.control_buttons_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.control_buttons_widget.setObjectName("control_buttons_widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_buttons_widget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.control_buttons_layout = QtWidgets.QHBoxLayout()
        self.control_buttons_layout.setObjectName("control_buttons_layout")

        self.play_button = QtWidgets.QPushButton(self.control_buttons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.play_button.sizePolicy().hasHeightForWidth())
        self.play_button.setSizePolicy(sizePolicy)
        self.play_button.setMaximumSize(QtCore.QSize(36, 32))
        self.play_button.setIconSize(QtCore.QSize(32, 32))
        self.play_button.setShortcut("")
        self.play_button.setObjectName("play_button")
        self.control_buttons_layout.addWidget(self.play_button)

        self.previous_button = QtWidgets.QPushButton(self.control_buttons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_button.sizePolicy().hasHeightForWidth())
        self.previous_button.setSizePolicy(sizePolicy)
        self.previous_button.setMaximumSize(QtCore.QSize(32, 32))
        self.previous_button.setIconSize(QtCore.QSize(32, 32))
        self.previous_button.setObjectName("previous_button")
        self.control_buttons_layout.addWidget(self.previous_button)

        self.next_button = QtWidgets.QPushButton(self.control_buttons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setMaximumSize(QtCore.QSize(32, 32))
        self.next_button.setObjectName("next_button")
        self.control_buttons_layout.addWidget(self.next_button)

        self.reverse_button = QtWidgets.QPushButton(self.control_buttons_widget)
        self.reverse_button.setCheckable(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverse_button.sizePolicy().hasHeightForWidth())
        self.reverse_button.setSizePolicy(sizePolicy)
        self.reverse_button.setMaximumSize(QtCore.QSize(32, 32))
        self.reverse_button.setObjectName("reverse_button")
        self.control_buttons_layout.addWidget(self.reverse_button)

        self.slow_button = QtWidgets.QPushButton(self.control_buttons_widget)
        self.slow_button.setCheckable(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slow_button.sizePolicy().hasHeightForWidth())
        self.slow_button.setSizePolicy(sizePolicy)
        self.slow_button.setMaximumSize(QtCore.QSize(32, 32))
        self.slow_button.setObjectName("slow_button")
        self.control_buttons_layout.addWidget(self.slow_button)

        self.record_gif_button = QtWidgets.QPushButton(self.control_buttons_widget)
        self.record_gif_button.setCheckable(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_gif_button.sizePolicy().hasHeightForWidth())
        self.record_gif_button.setSizePolicy(sizePolicy)
        self.record_gif_button.setMaximumSize(QtCore.QSize(32, 32))
        self.record_gif_button.setObjectName("record_gif_button")
        self.control_buttons_layout.addWidget(self.record_gif_button)

        self.control_buttons_layout.setStretch(4, 1)
        self.control_buttons_layout.setStretch(5, 1)
        self.verticalLayout.addLayout(self.control_buttons_layout)
        self.playback_speed_layout = QtWidgets.QHBoxLayout()
        self.playback_speed_layout.setObjectName("playback_speed_layout")
        self.playback_speed_label = QtWidgets.QLabel(self.control_buttons_widget)
        self.playback_speed_label.setObjectName("playback_speed_label")
        self.playback_speed_layout.addWidget(self.playback_speed_label)
        self.playback_speed_slider = QtWidgets.QSlider(self.control_buttons_widget)
        self.playback_speed_slider.setMinimum(1)
        self.playback_speed_slider.setMaximum(100)
        self.playback_speed_slider.setSliderPosition(100)
        self.playback_speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.playback_speed_slider.setObjectName("playback_speed_slider")
        self.playback_speed_layout.addWidget(self.playback_speed_slider)
        self.playback_speed_value_text = QtWidgets.QLabel(self.control_buttons_widget)
        self.playback_speed_value_text.setObjectName("playback_speed_value_text")
        self.playback_speed_layout.addWidget(self.playback_speed_value_text)
        self.playback_speed_layout.setStretch(0, 1)
        self.playback_speed_layout.setStretch(1, 10)
        self.playback_speed_layout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.playback_speed_layout)
        self.horizontalLayout.addWidget(self.control_buttons_widget)
        self.playback_slider_widget = QtWidgets.QWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playback_slider_widget.sizePolicy().hasHeightForWidth())
        self.playback_slider_widget.setSizePolicy(sizePolicy)
        self.playback_slider_widget.setObjectName("playback_slider_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.playback_slider_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.playback_slider = QtWidgets.QSlider(self.playback_slider_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playback_slider.sizePolicy().hasHeightForWidth())
        self.playback_slider.setSizePolicy(sizePolicy)
        self.playback_slider.setOrientation(QtCore.Qt.Horizontal)
        self.playback_slider.setObjectName("playback_slider")
        self.gridLayout_2.addWidget(self.playback_slider, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.playback_slider_widget)
        self.scan_index_timestamp_widget = QtWidgets.QWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_index_timestamp_widget.sizePolicy().hasHeightForWidth())
        self.scan_index_timestamp_widget.setSizePolicy(sizePolicy)
        self.scan_index_timestamp_widget.setObjectName("scan_index_timestamp_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.scan_index_timestamp_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.scan_index_label = QtWidgets.QLabel(self.scan_index_timestamp_widget)
        self.scan_index_label.setObjectName("scan_index_label")
        self.gridLayout.addWidget(self.scan_index_label, 0, 0, 1, 1)
        self.scan_index_text_field = QtWidgets.QLineEdit(self.scan_index_timestamp_widget)
        self.scan_index_text_field.setObjectName("scan_index_text_field")
        self.gridLayout.addWidget(self.scan_index_text_field, 0, 1, 1, 1)
        self.timestamp_label = QtWidgets.QLabel(self.scan_index_timestamp_widget)
        self.timestamp_label.setObjectName("timestamp_label")
        self.gridLayout.addWidget(self.timestamp_label, 1, 0, 1, 1)
        self.timestamp_text_field = QtWidgets.QLineEdit(self.scan_index_timestamp_widget)
        self.timestamp_text_field.setObjectName("timestamp_text_field")
        self.gridLayout.addWidget(self.timestamp_text_field, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.horizontalLayout.addWidget(self.scan_index_timestamp_widget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("PlaybackPanelWidget", "Form"))
        self.play_button.setText(_translate("PlaybackPanelWidget", "PLAY"))
        self.previous_button.setText(_translate("PlaybackPanelWidget", "<"))
        self.next_button.setText(_translate("PlaybackPanelWidget", ">"))
        self.reverse_button.setText(_translate("PlaybackPanelWidget", "R"))
        self.slow_button.setText(_translate("PlaybackPanelWidget", "S"))
        self.record_gif_button.setText(_translate("PlaybackPanelWidget", "REC"))
        self.playback_speed_label.setText(_translate("PlaybackPanelWidget", "Playback speed"))
        self.playback_speed_value_text.setText(_translate("PlaybackPanelWidget", "x 1.0"))
        self.scan_index_label.setText(_translate("PlaybackPanelWidget", "Scan index"))
        self.timestamp_label.setText(_translate("PlaybackPanelWidget", "Timestamp"))
