# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\wkspaces\aspe_gui\views\uis\settings_window_test.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets

from aspe.gui.views.settings.PointsDrawerSettingsWidget import PointsDrawerSettingsWidget


class SettingsWidgetTest(QtWidgets.QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("data_source_settings_widget")
        self.resize(287, 398)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMaximumSize(QtCore.QSize(450, 500))
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.data_set_settings_tab = QtWidgets.QTabWidget(self)
        self.data_set_settings_tab.setObjectName("data_set_settings_tab")

        self.data_set_1_tab = QtWidgets.QWidget()
        self.data_set_1_tab.setObjectName("data_set_1_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.data_set_1_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drawer_setting_group_box = QtWidgets.QGroupBox(self.data_set_1_tab)
        self.gridLayout_4 = QtWidgets.QGridLayout(self.drawer_setting_group_box)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.line_style_label = QtWidgets.QLabel(self.drawer_setting_group_box)
        self.gridLayout_5.addWidget(self.line_style_label, 2, 0, 1, 1)
        self.enabled_label = QtWidgets.QLabel(self.drawer_setting_group_box)
        self.gridLayout_5.addWidget(self.enabled_label, 0, 0, 1, 1)
        self.color_pickler_button = QtWidgets.QPushButton(self.drawer_setting_group_box)
        self.color_pickler_button.setText("")
        self.gridLayout_5.addWidget(self.color_pickler_button, 1, 1, 1, 1)
        self.is_enabled_check_box = QtWidgets.QCheckBox(self.drawer_setting_group_box)
        self.is_enabled_check_box.setText("")
        self.gridLayout_5.addWidget(self.is_enabled_check_box, 0, 1, 1, 1)
        self.color_label = QtWidgets.QLabel(self.drawer_setting_group_box)
        self.gridLayout_5.addWidget(self.color_label, 1, 0, 1, 1)
        self.line_style_combo_box = QtWidgets.QComboBox(self.drawer_setting_group_box)
        self.line_style_combo_box.addItem("")
        self.line_style_combo_box.addItem("")
        self.line_style_combo_box.addItem("")
        self.line_style_combo_box.addItem("")
        self.line_style_combo_box.addItem("")
        self.gridLayout_5.addWidget(self.line_style_combo_box, 2, 1, 1, 1)
        self.line_width_label = QtWidgets.QLabel(self.drawer_setting_group_box)
        self.gridLayout_5.addWidget(self.line_width_label, 3, 0, 1, 1)
        self.line_width_slider = QtWidgets.QSlider(self.drawer_setting_group_box)
        self.line_width_slider.setMinimum(1)
        self.line_width_slider.setMaximum(10)
        self.line_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gridLayout_5.addWidget(self.line_width_slider, 3, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.drawer_setting_group_box)
        self.data_set_settings_tab.addTab(self.data_set_1_tab, "")

        self.drawer_setting_group_box_2 = QtWidgets.QGroupBox(self.data_set_1_tab)
        self.drawer_setting_group_box_2.setObjectName("drawer_setting_group_box_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.drawer_setting_group_box_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.symbol_label = QtWidgets.QLabel(self.drawer_setting_group_box_2)
        self.symbol_label.setObjectName("symbol_label")
        self.gridLayout_7.addWidget(self.symbol_label, 2, 0, 1, 1)
        self.enabled_label_2 = QtWidgets.QLabel(self.drawer_setting_group_box_2)
        self.enabled_label_2.setObjectName("enabled_label_2")
        self.gridLayout_7.addWidget(self.enabled_label_2, 0, 0, 1, 1)
        self.color_pickler_button_2 = QtWidgets.QPushButton(self.drawer_setting_group_box_2)
        self.color_pickler_button_2.setText("")
        self.color_pickler_button_2.setObjectName("color_pickler_button_2")
        self.gridLayout_7.addWidget(self.color_pickler_button_2, 1, 1, 1, 1)
        self.is_enabled_check_box_2 = QtWidgets.QCheckBox(self.drawer_setting_group_box_2)
        self.is_enabled_check_box_2.setText("")
        self.is_enabled_check_box_2.setObjectName("is_enabled_check_box_2")
        self.gridLayout_7.addWidget(self.is_enabled_check_box_2, 0, 1, 1, 1)
        self.color_label_2 = QtWidgets.QLabel(self.drawer_setting_group_box_2)
        self.color_label_2.setObjectName("color_label_2")
        self.gridLayout_7.addWidget(self.color_label_2, 1, 0, 1, 1)
        self.symbol_combo_box = QtWidgets.QComboBox(self.drawer_setting_group_box_2)
        self.symbol_combo_box.setObjectName("symbol_combo_box")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.symbol_combo_box.addItem("")
        self.gridLayout_7.addWidget(self.symbol_combo_box, 2, 1, 1, 1)
        self.symbol_size_label = QtWidgets.QLabel(self.drawer_setting_group_box_2)
        self.symbol_size_label.setObjectName("symbol_size_label")
        self.gridLayout_7.addWidget(self.symbol_size_label, 3, 0, 1, 1)
        self.symbol_size_slider = QtWidgets.QSlider(self.drawer_setting_group_box_2)
        self.symbol_size_slider.setMinimum(1)
        self.symbol_size_slider.setMaximum(20)
        self.symbol_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.symbol_size_slider.setObjectName("symbol_size_slider")
        self.gridLayout_7.addWidget(self.symbol_size_slider, 3, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.drawer_setting_group_box_2)
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.data_set_settings_tab.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.data_set_settings_tab, 6, 0, 1, 1)

        self.data_set_settings_tab.addTab(PointsDrawerSettingsWidget('dupa', None, parent=self.data_set_settings_tab), 'dupa')
        self.retranslateUi()
        self.data_set_settings_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("data_source_settings_widget", "Form"))
        self.label_2.setText(_translate("data_source_settings_widget", "enabled"))
        self.drawer_setting_group_box.setTitle(_translate("data_source_settings_widget", "DrawerName"))
        self.line_style_label.setText(_translate("data_source_settings_widget", "line_style"))
        self.enabled_label.setText(_translate("data_source_settings_widget", "enabled"))
        self.color_label.setText(_translate("data_source_settings_widget", "color"))
        self.line_style_combo_box.setItemText(0, _translate("data_source_settings_widget", "-"))
        self.line_style_combo_box.setItemText(1, _translate("data_source_settings_widget", "--"))
        self.line_style_combo_box.setItemText(2, _translate("data_source_settings_widget", "-*-"))
        self.line_style_combo_box.setItemText(3, _translate("data_source_settings_widget", "***"))
        self.line_style_combo_box.setItemText(4, _translate("data_source_settings_widget", "-**-"))
        self.line_width_label.setText(_translate("data_source_settings_widget", "line_width"))
        self.drawer_setting_group_box_2.setTitle(_translate("data_source_settings_widget", "DrawerName"))
        self.symbol_label.setText(_translate("data_source_settings_widget", "symbol"))
        self.enabled_label_2.setText(_translate("data_source_settings_widget", "enabled"))
        self.color_label_2.setText(_translate("data_source_settings_widget", "color"))
        self.symbol_combo_box.setItemText(0, "o")
        self.symbol_combo_box.setItemText(1, "s")
        self.symbol_combo_box.setItemText(2, "+")
        self.symbol_combo_box.setItemText(3, "d")
        self.symbol_combo_box.setItemText(4, "t1")
        self.symbol_combo_box.setItemText(5, "t2")
        self.symbol_combo_box.setItemText(6, "t3")
        self.symbol_combo_box.setItemText(7, "p")
        self.symbol_combo_box.setItemText(8, "h")
        self.symbol_combo_box.setItemText(9, "star")
        self.symbol_size_label.setText(_translate("data_source_settings_widget", "symbol size"))
        self.data_set_settings_tab.setTabText(self.data_set_settings_tab.indexOf(self.data_set_1_tab), _translate("data_source_settings_widget", "Tab 1"))
        self.data_set_settings_tab.setTabText(self.data_set_settings_tab.indexOf(self.tab_2), _translate("data_source_settings_widget", "Tab 2"))
