load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "tracker_emb_lib",
    srcs = ["tracker_sil_wrapper.cpp"],
    hdrs = ["tracker_sil_wrapper.h"],
    strip_include_prefix = "//tracker_emb_lib",
    visibility = ["//visibility:public"],
)
