BMW_ASPE_SIGNAL_MAPPER = {
    'x-position of reference point':    'dev_position_x',
    'std x':                            'nees_value_position_x',
    'y-position of reference point':    'dev_position_y',
    'std y':                            'nees_value_position_y',
    'covariance x y':                   'nees_value_position_xy',
    'vx abs':                      'dev_velocity_x',
    'std vx abs':                       'nees_value_velocity_x',
    'vy abs':                      'dev_velocity_y',
    'std vy abs':                       'nees_value_velocity_y',
    'covariance vx vy':                 'nees_value_velocity_xy',
    'vx rel':                           'dev_velocity_rel_x',
    'std vx rel':                       '',
    'vy rel':                           'dev_velocity_rel_y',
    'std vy rel':                       '',
    'length':                           'dev_bounding_box_dimensions_x',
    'std length':                       '',
    'width':                            'dev_bounding_box_dimensions_y',
    'std width':                        '',
    'change rate of orientation angle': 'dev_yaw_rate',
    'std orientation':                  '',
    'orientation angle':                'dev_orientation',
    'std yaw rate':                     '',
    'ax abs':                           'dev_acceleration_otg_x',
    'std ax abs':                       '',
    'ay abs':                           'dev_acceleration_otg_y',
    'std ax abs':                       '',
    'ax rel':                           'dev_acceleration_rel_x',
    'std ax rel':                       '',
    'ay rel':                           'dev_acceleration_rel_y',
    'std ay rel':                       '',
    'object detection rate':            '',
    'type/class':                       '',
}
