"""
Scenario Generator Radars Mounting Location Enum
"""

from enum import Enum


class ScenGenRadarsMountingLocation(Enum):
    ScGn_MOUNTING_LOCATION_UNKNOWN = -1
    ScGn_MOUNTING_LOCATION_LEFT_FORWARD = 0
    ScGn_MOUNTING_LOCATION_LEFT_SIDE1 = 8
    ScGn_MOUNTING_LOCATION_LEFT_SIDE2 = 16
    ScGn_MOUNTING_LOCATION_LEFT_REAR = 24
    ScGn_MOUNTING_LOCATION_CENTER_FORWARD = 1
    ScGn_MOUNTING_LOCATION_CENTER_REAR = 25
    ScGn_MOUNTING_LOCATION_RIGHT_FORWARD = 2
    ScGn_MOUNTING_LOCATION_RIGHT_SIDE1 = 10
    ScGn_MOUNTING_LOCATION_RIGHT_SIDE2 = 18
    ScGn_MOUNTING_LOCATION_RIGHT_REAR = 26
    ScGn_MOUNTING_LOCATION_CENTER2_FORWARD = 3
    ScGn_MOUNTING_LOCATION_CENTER2_REAR = 27
    ScGn_MOUNTING_LOCATION_CENTER_CENTER_360 = 255
    