cc_test(
    name = "iface_variant_C_test",
    srcs = ["test.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//tracker_emb_lib/F360Tracker/F360TrackerLib:libf360_variant_C_Logging",
        "//tracker_emb_lib/F360Tracker/F360TrackerLib:libf360_variant_C_Type",
        "//tracker_emb_lib/F360Tracker/F360TrackerLib:libf360_variant_C_a",
        "//tracker_emb_lib/F360Tracker/F360TrackerLib:libf360_variant_C_core",
        "//tracker_emb_lib/F360Tracker/rspp:librspp_variant_C_a",
        "//tracker_emb_lib/F360Tracker/rspp:rspp_iface_variant_C",
    ],
)
