[tool.pytest.ini_options]
# See: https://docs.pytest.org/en/latest/reference/reference.html#ini-options-ref
# Run with "pytest" in the root
console_output_style = "count"
log_cli = true
addopts = "--cov=. --cov-report=html --capture=no --show-capture=no"
testpaths =[
    "tests",
]

[tool.coverage.run]
# This part is intended for the pytest-cov settings.
# See: https://coverage.readthedocs.io/en/latest/config.html
source = ["."]
omit =[
    "*/__init__.py",
    "*/tests/*",
    "setup.py",
]
branch = true

[tool.coverage.report]
show_missing = true
exclude_also = [
    #Don't complain if non-runnable code isn't run
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]

[tool.ruff]
# Ruff linter configuration

select = [
    "E", "F", "PT", "COM", "C4", "ISC", "ICN", "INP", "Q", "RET", "SLF", "PTH", "RUF", "PL", "I", "YTT", "S",
    "B", "DTZ", "EXE", "ISC", "SIM"
]

extend-select = ["C4", "SIM", "TCH"]

ignore = [
    "S101", "PLR0913",
    "E712", # caused some problems with dataframe filtering
    "Q000", # use double quotes, don't seem to be relevant, caused lots of confusion

]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = []
unfixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM",
    "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH",
    "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

extend-exclude = ["uis", # autogenerated code from QtCreator
    "report_generator",
    "tests",
    "sandbox",
    "docs"]

per-file-ignores = {}

line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.7.
target-version = "py37"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10