set(REL_PATH Fusion360/initialize_tracks)

set(SRC_LOCAL
    ${REL_PATH}/include/f360_fill_init_obj_track_props.h
    ${REL_PATH}/include/f360_initialization_preconditions.h
    ${REL_PATH}/include/f360_initialize_tracks.h
    ${REL_PATH}/include/f360_is_cluster_affected_by_angle_jumps.h
    ${REL_PATH}/include/f360_is_cluster_visible.h
    ${REL_PATH}/include/f360_is_cluster_vs_object_prioritization_succeed.h
    ${REL_PATH}/include/f360_nees_cfmi_helpers.h
    ${REL_PATH}/include/f360_nees_cfmi_hypotheses_selector.h
    ${REL_PATH}/include/f360_nees_cfmi_hypothesis_cloud.h
    ${REL_PATH}/include/f360_nees_cfmi_hypothesis_confirm_pos_diff.h
    ${REL_PATH}/include/f360_nees_cfmi_hypothesis_dominant_velocity.h
    ${REL_PATH}/include/f360_nees_cfmi_hypothesis_radial.h
    ${REL_PATH}/include/f360_nees_cfmi_info_cloud.h
    ${REL_PATH}/include/f360_nees_cfmi_info_pos_diff.h
    ${REL_PATH}/include/f360_nees_cfmi_information_processing.h
    ${REL_PATH}/include/f360_nees_cfmi_inliers_check.h
    ${REL_PATH}/include/f360_nees_cfmi_m_estimator.h
    ${REL_PATH}/include/f360_nees_cfmi_minimization.h
    ${REL_PATH}/include/f360_nees_cfmi_post_processing.h
    ${REL_PATH}/include/f360_nees_cfmi_post_processing_internals.h
    ${REL_PATH}/include/f360_nees_cfmi_preconditions.h
    ${REL_PATH}/include/f360_nees_cfmi_ransac.h
    ${REL_PATH}/include/f360_nees_cfmi_stationary_checks.h
    ${REL_PATH}/include/f360_nees_cfmi_structs.h
    ${REL_PATH}/include/f360_nees_cfmi_try_to_init.h
    ${REL_PATH}/include/f360_sort_clusters_by_priority.h
    ${REL_PATH}/include/f360_calc_object_init_ep.h
    ${REL_PATH}/include/f360_detection_history_time_slots_processing.h
    ${REL_PATH}/source/f360_nees_cfmi_hypothesis_confirm_pos_diff.cpp
    ${REL_PATH}/source/f360_nees_cfmi_hypothesis_dominant_velocity.cpp
    ${REL_PATH}/source/f360_nees_cfmi_hypothesis_radial.cpp
    ${REL_PATH}/source/f360_nees_cfmi_info_cloud.cpp
    ${REL_PATH}/source/f360_nees_cfmi_info_pos_diff.cpp
    ${REL_PATH}/source/f360_nees_cfmi_information_processing.cpp
    ${REL_PATH}/source/f360_nees_cfmi_inliers_check.cpp
    ${REL_PATH}/source/f360_nees_cfmi_m_estimator.cpp
    ${REL_PATH}/source/f360_nees_cfmi_minimization.cpp
    ${REL_PATH}/source/f360_nees_cfmi_post_processing.cpp
    ${REL_PATH}/source/f360_nees_cfmi_post_processing_internals.cpp
    ${REL_PATH}/source/f360_nees_cfmi_preconditions.cpp
    ${REL_PATH}/source/f360_nees_cfmi_ransac.cpp
    ${REL_PATH}/source/f360_nees_cfmi_stationary_checks.cpp
    ${REL_PATH}/source/f360_nees_cfmi_structs.cpp
    ${REL_PATH}/source/f360_nees_cfmi_try_to_init.cpp
    ${REL_PATH}/source/f360_sort_clusters_by_priority.cpp
    ${REL_PATH}/source/f360_calc_object_init_ep.cpp
    ${REL_PATH}/source/f360_detection_history_time_slots_processing.cpp
    ${REL_PATH}/source/f360_fill_init_obj_track_props.cpp
    ${REL_PATH}/source/f360_initialization_preconditions.cpp
    ${REL_PATH}/source/f360_initialize_tracks.cpp
    ${REL_PATH}/source/f360_is_cluster_affected_by_angle_jumps.cpp
    ${REL_PATH}/source/f360_is_cluster_visible.cpp
    ${REL_PATH}/source/f360_is_cluster_vs_object_prioritization_succeed.cpp
    ${REL_PATH}/source/f360_nees_cfmi_helpers.cpp
    ${REL_PATH}/source/f360_nees_cfmi_hypotheses_selector.cpp
    ${REL_PATH}/source/f360_nees_cfmi_hypothesis_cloud.cpp
)

set(SRC ${SRC} ${SRC_LOCAL})
